title: Security
path: cctv
icon: mdi:cctv
cards:
  - type: vertical-stack
    cards:
      - type: picture-glance
        title: Детская
        entities:
          - light.detskaia
        camera_image: camera.dafangcam_03_rtsp
      - type: entities
        show_header_toggle: false
        entities:
          - entity: automation.dvizhenie_v_detskoi
            name: Контроль движения в Детской
            icon: mdi:motion-sensor
  - type: picture-glance
    title: Гостиная
    entities:
      - light.sonoff_1000f30a9e
    camera_image: camera.dafangcam_01_rtsp
  - type: picture-glance
    title: Прихожая
    entities:
      - light.sonoff_1000f2f14a
    camera_image: camera.dafangcam_02_rtsp
