#################################################
# Miscellaneous binary sensors
#################################################

- platform: workday
  country: RU
- platform: tod
  name: time_between_17_21
  after: '17:00'
  before: '21:00'
- platform: tod
  name: time_between_7_10
  after: '7:00'
  before: '10:00'
- platform: template
  sensors:
    updater_supervisor:
      friendly_name: 'Updater - Supervisor'
      device_class: problem
      value_template: "{{ state_attr('sensor.supervisor_updates', 'current_version') != state_attr('sensor.supervisor_updates', 'newest_version') }}"
      availability_template: "{{ (states('sensor.supervisor_updates') | int(-1)) > -1 }}"
    updater_addons:
      friendly_name: 'Updater - Addons'
      device_class: problem
      value_template: "{{ states('sensor.supervisor_updates') | int > 0 }}"
    humidifier_nursery_status:
      device_class: power
      value_template: "{{ is_state('fan.xiaomi_miio_device', 'on') }}"
    boiler_status:
      device_class: power
      value_template: "{{ is_state('switch.tplink_smartplug_01', 'on') }}"