#################################################
# Lamp binary sensors
#################################################

- platform: template
  sensors:
    lamp_status_spalnia_stol:
      device_class: power
      value_template: "{{ is_state('light.spalnia_stol', 'on') }}"
    lamp_status_detskaia:
      device_class: power
      value_template: "{{ is_state('light.detskaia', 'on') }}"
    lamp_status_detskaia_okno:
      device_class: power
      value_template: "{{ is_state('light.detskaia_podsvetka_na_okne', 'on') }}"
    lamp_status_gostinaia_okno:
      device_class: power
      value_template: "{{ is_state('light.gostinaia_podsvetka_na_okne', 'on') }}"
    lamp_status_gostinaya_bra:
      device_class: power
      value_template: "{{ is_state('light.sonoff_1000ab3c28', 'on') }}"
    lamp_status_gostinaya_liustra:
      device_class: power
      value_template: "{{ is_state('light.sonoff_1000f3035d', 'on') }}"
    lamp_status_gostinaya_spots:
      device_class: power
      value_template: "{{ is_state('light.sonoff_1000f30a9e', 'on') }}"
    lamp_status_kukhnia_lenta:
      device_class: power
      value_template: "{{ is_state('light.kukhnia_lenta', 'on') }}"
    lamp_status_kukhnia_liustra:
      device_class: power
      value_template: "{{ is_state('light.kukhnia_liustra', 'on') }}"
    lamp_status_kukhnia_spots:
      value_template: "{{ is_state('light.sonoff_1000b72483', 'on') }}"
    lamp_status_kladovaya:
      device_class: power
      value_template: "{{ is_state('light.sonoff_1000b6831b', 'on') }}"
    lamp_status_workdesk_gostinaya:
      device_class: power
      value_template: "{{ is_state('light.0x86bd7fffe616b72_light', 'on') }}"
    lamp_status_prikhozhaya:
      value_template: "{{ is_state('light.sonoff_1000f2f14a', 'on') }}"
    lamp_status_koridor:
      value_template: "{{ is_state('light.sonoff_1000f2a500', 'on') }}"