esphome:
  name: ${board_name}
  platform: ${esp_platform}
  board: ${esp_board}

captive_portal:

logger:
  baud_rate: 0

api:
  password: !secret esphome_api_password
  reboot_timeout: 5min

ota:
  password: !secret esphome_api_password

#web_server:
#  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: wifi_signal
    name: ${board_name}_wifi_rssi
    update_interval: 60s
    internal: false

binary_sensor:
  - platform: status
    name: ${board_name}_status
    internal: false

switch:
  - platform: restart
    name: ${board_name}_restart