wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 15min
  fast_connect: true
  power_save_mode: none
  ap:
    ssid: ${board_name}
    password: !secret wifi_fallback_ap_pass