#################################################
# Media automatization
#################################################

- alias: 'PowerOff all media when nobody at home'
  initial_state: true
  trigger:
    platform: state
    entity_id: group.family_persons
    to: "not_home"
    for:
      minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.all_tv
        state: "on"
      - condition: state
        entity_id: group.all_chromecasts
        state: "on"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_tv
    - service: media_player.media_stop
      data:
        entity_id: group.all_chromecasts

- alias: 'Громкость радио'
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.output_device", "Гостинная (TV)") %} media_player.gostinaia
        {% elif is_state("input_select.output_device", "Гостинная (Home Mini)") %} media_player.googlehome9967
        {% elif is_state("input_select.output_device", "Детская (TV)") %} media_player.detskaia
        {% elif is_state("input_select.output_device", "Детская (Home Mini)") %} media_player.googlehome3792
        {% endif %}
      volume_level: '{{  states.input_number.volume_radio.state  }}'

- alias: 'Wakeup Radio - Childrens'
  initial_state: true
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states('input_datetime.wakeup_radio_in_nursery')[:5]) }}"
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    - service: media_player.volume_set
      entity_id: media_player.googlehome3792
      data:
        volume_level: "0.1"
    - service: media_player.play_media
      data:
        entity_id: media_player.googlehome3792
        media_content_id: "http://ic7.101.ru:8000/a199"
        media_content_type: music
    - service: automation.turn_on
      entity_id: automation.increase_volume_loop_childrens_room
    - delay:
        minutes: 18
    - service: automation.turn_off
      entity_id: automation.increase_volume_loop_childrens_room

- alias: Increase volume loop - Childrens Room
  initial_state: false
  trigger:
    platform: time_pattern
    minutes: "/3"
  action:
    - service: script.turn_on
      entity_id: script.googlehome3792_increase_volume