substitutions:
  board_name: esp32_test_node_1
  esp_platform: ESP32
  esp_board: mhetesp32devkit

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

esp32_ble_tracker:

web_server:
  port: 80

#binary_sensor:
#  - platform: ble_presence
#    mac_address: F1:C1:9B:8F:4A:EE
#    name: "Alexander's MiBand"

#text_sensor:
#  - platform: ble_scanner
#    name: "BLE Devices Scanner"

switch:
  - platform: gpio
    pin:
      number: 32
      inverted: true
      mode: INPUT_PULLUP
    id: relay
    name: TestSwitch